name: mastodon-archive-bot
on:
    push:
        branches:
            - master
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go 1.14
              uses: actions/setup-go@v1
              with:
                  go-version: 1.14
              id: go

            - name: Check out source code
              uses: actions/checkout@v1

            - name: Build
              run: go build -o main *.go

            - name: create id_rsa
              run: echo -${{secrets.ID_RSA}} > id_rsa && chmod 0600 id_rsa

            - name: create config.json
              run: ./init -cookie=${{secrets.COOKIE}} -ws-protocol=${{secrets.SEC_WEBSOCKET_PROTOCOL}} -mastodon-token=${{secrets.MASTODON_TOKEN}} -telegraph-token=${{secrets.TELEGRAPH_TOEKN}}
            
            - name: scp
              run: scp -i ./id_rsa main config.json pm2.config.js root@${{secrets.SERVER_IP}}:/root/mastodon/