name: mastodon-archive-bot
on:
    push:
        branches:
            - master
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go 1.14
              uses: actions/setup-go@v1
              with:
                  go-version: 1.14
              id: go

            - name: Check out source code
              uses: actions/checkout@v1

            - name: Build
              run: |
                go build -o deploy/main *.go

            - name: create config.json
              run: ./deploy/init -cookie="${{secrets.COOKIE}}" -ws-protocol="${{secrets.SEC_WEBSOCKET_PROTOCOL}}" -mastodon-token="${{secrets.MASTODON_TOKEN}}" -telegraph-token="${{secrets.TELEGRAPH_TOEKN}}" && pwd
            
            - name: deploy
              uses: horochx/deploy-via-scp@master
              with:
                local: deploy # eg: dist
                remote: /root/mastodon # eg: /home/github-action
                host: ${{ secrets.SERVER_IP }} # eg: example.com
                port: 22 # eg: 22
                user: root # eg: github-action
                key: ${{ secrets.ID_RSA }} # 