name: mastodon-archive-bot
on:
    push:
        branches:
            - master
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go 1.14
              uses: actions/setup-go@v1
              with:
                  go-version: 1.14
              id: go

            - name: Check out source code
              uses: actions/checkout@v1

            - name: Build
              run: |
                  go build -o mastodon/main *.go

            - name: create config.json
              run: ./mastodon/init -cookie="${{secrets.COOKIE}}" -ws-protocol="${{secrets.SEC_WEBSOCKET_PROTOCOL}}" -mastodon-token="${{secrets.MASTODON_TOKEN}}" -telegraph-token="${{secrets.TELEGRAPH_TOEKN}}" && mv config.json ./mastodon/

            - name: deploy to remote server
              uses: garygrossgarten/github-action-scp@release
              with:
                  local: mastodon
                  remote: /root/mastodon/
                  host: ${{ secrets.SERVER_IP }}
                  username: root
                  privateKey: ${{ secrets.ID_RSA }}
